name = "Notron"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE"
description = "Jason Rigden's Theme for Hugo"
homepage = "https://github.com/vimux/blank/"
tags = ["blog"]
features = ["blog"]
min_version = "1.0.0"

[author]
  name = "Jason Rigden"
  homepage = "https://rigden.dev"
